<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SampleMod</AssemblyName>
    <RootNamespace>SampleMod</RootNamespace>
    <Authors>Your_Name</Authors>
    <TargetFramework>net4.7.2</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.0.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="..\Libs\*.dll">
      <Private>false</Private>
    </Reference>

    <Reference Include="..\SrmlLibs\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="modinfo.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>