<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SRML</AssemblyName>
    <RootNamespace>SRML</RootNamespace>
    <Authors>SlimeRancherModding</Authors>
    <Description>Mod Loader for the game Slime Rancher</Description>
    <Version>0.3.0.0</Version>
    <TargetFramework>net4.7.2</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <PackageLicenseExpression>GPL-3.0</PackageLicenseExpression>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="..\Libs\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.3.6" />
    <PackageReference Include="ini-parser" Version="2.5.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.12.11" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.12.11" PrivateAssets="all" ExcludeAssets="runtime" />
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.12.11" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <Publicize Include="Assembly-CSharp" IncludeCompilerGeneratedMembers="false" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="srml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SRML.Editor\SRML.Editor.csproj" />
  </ItemGroup>
</Project>